### ISSUE TITLE
Invalid image_id.

### ISSUE THREAD

**Issue by erickyellott** [rozap/minnowswithmachineguns#1]
Using image_id: 25489 is resulting in an error:

```
{"status":"ERROR","error_message":"You specified an invalid image for Droplet creation."}
```

An aside, pulling error messages out of dop could be done a lot mo' betta.

When I hit the DO API, I'm seeing:

```
{"id":284203,"name":"Ubuntu 12.04 x64","slug":null,"distribution":"Ubuntu","public":true},
{"id":284211,"name":"Ubuntu 12.04 x32","slug":null,"distribution":"Ubuntu","public":true}
```

Maybe we should search the images based on `"name"` and pull out the id, although I'm not sure why the id would have changed. Changing it out made it work correctly.

**Comment by rozap** [comment]
Alright I'll take a look at this soon. What ID are you using that works?
